[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.8",
    "langchain>=0.3.19",
    "python-dotenv>=1.0.1",
    "structlog>=25.1.0",
    "uvicorn>=0.34.0",
]
